-- Supabase / PostgreSQL Schema Optimized for Gastros App

CREATE TABLE gastos (
  -- BIGINT Identity is standard for Supabase scalable IDs
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Form Fields
  local TEXT NOT NULL,
  proveedor TEXT NOT NULL,
  fecha_servicio DATE NOT NULL,
  fecha_pago DATE NOT NULL,
  detalle_servicio TEXT,
  detalle_pago TEXT,
  moneda TEXT NOT NULL CHECK (moneda IN ('peso', 'usd')),
  monto DECIMAL(15, 2) NOT NULL,
  categoria TEXT NOT NULL,
  evento TEXT NOT NULL CHECK (evento IN ('normal', 'especial')),
  
  -- File Handling
  comprobante_url TEXT, -- Use this for the binary/filename if needed
  file_drive_url TEXT,  -- The Google Drive 'webContentLink' goes here
  
  -- Workflow Status
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'PAID')),
  
  -- Timestamps
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance on the Dashboard
CREATE INDEX idx_gastos_status ON gastos(status);
CREATE INDEX idx_gastos_fecha_servicio ON gastos(fecha_servicio);

-- Optional: Enable Row Level Security (RLS) if you plan to use Supabase JS Client directly in the future
-- ALTER TABLE gastos ENABLE ROW LEVEL SECURITY;
